version: 2.1

orbs:
  python: circleci/python@2.1.1
  postgres: circleci/postgres@2.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - postgres/start:
          version: 13.5
          username: testuser
          password: testpass
          database: testdb
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run migrations
          command: |
            python manage.py migrate
      - run:
          name: Run tests
          command: |
            python manage.py test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test