version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:13.5
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz | tar -xz
            mv docker/docker /usr/bin/docker
            chmod +x /usr/bin/docker
      - run:
          name: Build and test
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python manage.py test
      - run:
          name: Build Docker image
          command: |
            docker build -t django-auth-api .